import { getEnv } from "@/lib/env";
import { all, one, run } from "@/lib/db";

export const EXPIRY_OPTIONS = [0, 3_600_000, 6 * 3_600_000, 24 * 3_600_000, 3 * 24 * 3_600_000, 7 * 24 * 3_600_000];
const PAGE_SIZE = 20;
const id = () => crypto.randomUUID();
const active = (emailId: string) => one<TempEmail>("SELECT * FROM email WHERE id=? AND expires_at>?", emailId, Date.now());
export type TempEmail = { id:string;address:string;tag:string|null;is_custom:number;userId:string|null;group_id:string|null;sort_order:number|null;created_at:number;expires_at:number };

export async function listTemporaryMailboxes(offset=0,loadAll=false) { const now=Date.now(); const rows=await all<TempEmail>(`SELECT * FROM email WHERE expires_at>? ORDER BY CASE WHEN sort_order IS NULL THEN 1 ELSE 0 END,sort_order ASC,created_at DESC,id DESC ${loadAll ? "" : "LIMIT ? OFFSET ?"}`,now,...(loadAll ? [] : [PAGE_SIZE+1,offset])); const hasMore=!loadAll && rows.length>PAGE_SIZE; const domains=(await getEnv().SITE_CONFIG.get("EMAIL_DOMAINS"))?.split(",").map((item: string)=>item.trim()).filter(Boolean) || []; return {emails:hasMore ? rows.slice(0,PAGE_SIZE) : rows,nextCursor:hasMore ? String(offset+PAGE_SIZE) : null,total:(await one<{count:number}>("SELECT COUNT(*) count FROM email WHERE expires_at>?",now))?.count || 0,domains}; }
export async function generateTemporaryMailbox(input:{name?:string;expiryTime?:number;domain?:string;tag?:string|null;isCustom?:boolean}) { if(input.isCustom) throw new TempError("不支持自定义完整邮箱地址",400); if(!EXPIRY_OPTIONS.includes(input.expiryTime || -1)) throw new TempError("无效的过期时间",400); const domains=(await getEnv().SITE_CONFIG.get("EMAIL_DOMAINS"))?.split(",").map((item: string)=>item.trim()).filter(Boolean) || []; if(!input.domain || !domains.includes(input.domain)) throw new TempError("无效的域名",400); const prefix=(input.name || randomPrefix()).trim().toLowerCase(); if(!/^[a-z0-9][a-z0-9_-]{0,63}$/i.test(prefix)) throw new TempError("邮箱前缀只能包含字母、数字、下划线和连字符，且必须以字母或数字开头",400); const tag=input.tag?.trim() || null; if(tag && tag.length>32) throw new TempError("标签不能超过 32 个字符",400); const address=`${prefix}@${input.domain}`; if(await one("SELECT id FROM email WHERE address=? COLLATE NOCASE",address)) throw new TempError("已经有这个邮箱地址了，请换一个名称或域名",409); const now=Date.now(); const mailbox={id:id(),address,tag,is_custom:0,userId:null,group_id:null,sort_order:-now,created_at:now,expires_at:input.expiryTime===0 ? Date.parse("9999-01-01T00:00:00.000Z") : now+(input.expiryTime || 0)}; await run("INSERT INTO email (id,address,tag,is_custom,userId,group_id,sort_order,created_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?)",mailbox.id,mailbox.address,mailbox.tag,0,null,null,mailbox.sort_order,mailbox.created_at,mailbox.expires_at); return {id:mailbox.id,email:mailbox.address}; }
export async function getMailbox(id:string){return active(id);}
export async function updateMailbox(id:string,input:{expiryTime?:number;tag?:string|null}){ if(!await active(id)) throw new TempError("邮箱不存在",404); const fields:string[]=[];const params:unknown[]=[]; if("expiryTime" in input){if(!EXPIRY_OPTIONS.includes(input.expiryTime || -1)) throw new TempError("无效的过期时间",400);fields.push("expires_at=?");params.push(input.expiryTime===0 ? Date.parse("9999-01-01T00:00:00.000Z") : Date.now()+(input.expiryTime || 0));} if("tag" in input){fields.push("tag=?");params.push(input.tag?.trim() || null);} if(fields.length)await run(`UPDATE email SET ${fields.join(",")} WHERE id=?`,...params,id); return one<TempEmail>("SELECT * FROM email WHERE id=?",id);}
export async function deleteMailbox(id:string){if(!await active(id))throw new TempError("邮箱不存在",404);await run("DELETE FROM message WHERE source='temporary' AND emailId=?",id);await run("DELETE FROM email WHERE id=?",id);}
export async function listTemporaryMessages(emailId:string,cursor?:string|null,summary=false,countOnly=false){if(!await active(emailId))throw new TempError("邮箱不存在",404);let where="source='temporary' AND emailId=? AND type='received'";const args:unknown[]=[emailId];if(cursor){const [at,messageId]=cursor.split(":");if(at && messageId){where+=" AND (received_at<? OR (received_at=? AND id<?))";args.push(Number(at),Number(at),messageId);}}const total=(await one<{count:number}>(`SELECT COUNT(*) count FROM message WHERE ${where}`,...args))?.count || 0;if(countOnly)return {messages:[],nextCursor:null,total};const rows=await all<Record<string,unknown>&{id:string;received_at:number}>(`SELECT id,from_address,to_address,subject,content,html,received_at,sent_at,type,is_read FROM message WHERE ${where} ORDER BY received_at DESC,id DESC LIMIT ?`,...args,PAGE_SIZE+1);const more=rows.length>PAGE_SIZE;const list=(more?rows.slice(0,PAGE_SIZE):rows).map(row=>({id:row.id,from_address:row.from_address,to_address:row.to_address,subject:row.subject,content:summary?undefined:row.content,html:summary?undefined:row.html,received_at:row.received_at,sent_at:row.sent_at,type:row.type,is_read:Boolean(row.is_read)}));const last=list.at(-1);return{messages:list,nextCursor:more&&last?`${last.received_at}:${last.id}`:null,total};}
export async function temporaryMessage(emailId:string,messageId:string){if(!await active(emailId))throw new TempError("邮箱不存在",404);return one<Record<string,unknown>>("SELECT id,from_address,to_address,subject,content,html,received_at,sent_at,type,is_read FROM message WHERE id=? AND emailId=? AND source='temporary'",messageId,emailId);}
export async function markTemporaryMessage(emailId:string,messageId:string,isRead:boolean){if(!await active(emailId))throw new TempError("邮箱不存在",404);const changed=await run("UPDATE message SET is_read=?,updated_at=? WHERE id=? AND emailId=? AND source='temporary'",isRead?1:0,Date.now(),messageId,emailId);if(!changed.meta.changes)throw new TempError("邮件不存在",404);return{id:messageId,isRead};}
export async function deleteTemporaryMessage(emailId:string,messageId:string){if(!await active(emailId))throw new TempError("邮箱不存在",404);const changed=await run("DELETE FROM message WHERE id=? AND emailId=? AND source='temporary'",messageId,emailId);if(!changed.meta.changes)throw new TempError("邮件不存在或已删除",404);}
export class TempError extends Error {constructor(message:string,public status:number){super(message);}}
function randomPrefix(){return crypto.randomUUID().replace(/-/g,"").slice(0,12);}
